Exploratory Data Analysis

In [20]:
import pandas as pd
import sqlite3

In [21]:
conn=sqlite3.connect('inventory.db')

In [22]:
tables=pd.read_sql_query("Select name from sqlite_master Where type='table'",conn)
tables

              name
0  begin_inventory
1    end_inventory
2        purchases
3  purchase_prices
4            sales
5   vendor_invoice

In [23]:
for table in tables['name']:
    print('-'*50,f'{table}','-'*50)
    print('Count of records:',pd.read_sql(f"Select count(*) as count  from {table}",conn)['count'].values[0])
    display(pd.read_sql(f"select * from {table} limit 5",conn))

-------------------------------------------------- begin_inventory --------------------------------------------------
Count of records: 206529

,InventoryId,Store,City,Brand,Description,Size,onHand,Price,startDate
0,1_HARDERSFIELD_58,1,HARDERSFIELD,58,Gekkeikan Black & Gold Sake,750mL,8,12.99,01-01-2024
1,1_HARDERSFIELD_60,1,HARDERSFIELD,60,Canadian Club 1858 VAP,750mL,7,10.99,01-01-2024
2,1_HARDERSFIELD_62,1,HARDERSFIELD,62,Herradura Silver Tequila,750mL,6,36.99,01-01-2024
3,1_HARDERSFIELD_63,1,HARDERSFIELD,63,Herradura Reposado Tequila,750mL,3,38.99,01-01-2024
4,1_HARDERSFIELD_72,1,HARDERSFIELD,72,No. 3 London Dry Gin,750mL,6,34.99,01-01-2024

-------------------------------------------------- end_inventory --------------------------------------------------
Count of records: 224489

,InventoryId,Store,City,Brand,Description,Size,onHand,Price,endDate
0,1_HARDERSFIELD_58,1,HARDERSFIELD,58,Gekkeikan Black & Gold Sake,750mL,11,12.99,31-12-2024
1,1_HARDERSFIELD_62,1,HARDERSFIELD,62,Herradura Silver Tequila,750mL,7,36.99,31-12-2024
2,1_HARDERSFIELD_63,1,HARDERSFIELD,63,Herradura Reposado Tequila,750mL,7,38.99,31-12-2024
3,1_HARDERSFIELD_72,1,HARDERSFIELD,72,No. 3 London Dry Gin,750mL,4,34.99,31-12-2024
4,1_HARDERSFIELD_75,1,HARDERSFIELD,75,Three Olives Tomato Vodka,750mL,7,14.99,31-12-2024

-------------------------------------------------- purchases --------------------------------------------------
Count of records: 1048575

,InventoryId,Store,Brand,Description,Size,VendorNumber,VendorName,PONumber,PODate,ReceivingDate,InvoiceDate,PayDate,PurchasePrice,Quantity,Dollars,Classification
0,69_MOUNTMEND_8412,69,8412,Tequila Ocho Plata Fresno,750mL,105,ALTAMAR BRANDS LLC,8124,21-12-2023,02-01-2024,04-01-2024,16-02-2024,35.71,6,214.26,1
1,30_CULCHETH_5255,30,5255,TGI Fridays Ultimte Mudslide,1.75L,4466,AMERICAN VINTAGE BEVERAGE,8137,22-12-2023,01-01-2024,07-01-2024,21-02-2024,9.35,4,37.40,1
2,34_PITMERDEN_5215,34,5215,TGI Fridays Long Island Iced,1.75L,4466,AMERICAN VINTAGE BEVERAGE,8137,22-12-2023,02-01-2024,07-01-2024,21-02-2024,9.41,5,47.05,1
3,1_HARDERSFIELD_5255,1,5255,TGI Fridays Ultimte Mudslide,1.75L,4466,AMERICAN VINTAGE BEVERAGE,8137,22-12-2023,01-01-2024,07-01-2024,21-02-2024,9.35,6,56.10,1
4,76_DONCASTER_2034,76,2034,Glendalough Double Barrel,750mL,388,ATLANTIC IMPORTING COMPANY,8169,24-12-2023,02-01-2024,09-01-2024,16-02-2024,21.32,5,106.60,1

-------------------------------------------------- purchase_prices --------------------------------------------------
Count of records: 12261

,Brand,Description,Price,Size,Volume,Classification,PurchasePrice,VendorNumber,VendorName
0,58,Gekkeikan Black & Gold Sake,12.99,750mL,750,1,9.28,8320,SHAW ROSS INT L IMP LTD
1,62,Herradura Silver Tequila,36.99,750mL,750,1,28.67,1128,BROWN-FORMAN CORP
2,63,Herradura Reposado Tequila,38.99,750mL,750,1,30.46,1128,BROWN-FORMAN CORP
3,72,No. 3 London Dry Gin,34.99,750mL,750,1,26.11,9165,ULTRA BEVERAGE COMPANY LLP
4,75,Three Olives Tomato Vodka,14.99,750mL,750,1,10.94,7245,PROXIMO SPIRITS INC.

-------------------------------------------------- sales --------------------------------------------------
Count of records: 1048575

,InventoryId,Store,Brand,Description,Size,SalesQuantity,SalesDollars,SalesPrice,SalesDate,Volume,Classification,ExciseTax,VendorNo,VendorName
0,1_HARDERSFIELD_1004,1,1004,Jim Beam w/2 Rocks Glasses,750mL,1,16.49,16.49,01-01-2024,750,1,0.79,12546,JIM BEAM BRANDS COMPANY
1,1_HARDERSFIELD_1004,1,1004,Jim Beam w/2 Rocks Glasses,750mL,2,32.98,16.49,02-01-2024,750,1,1.57,12546,JIM BEAM BRANDS COMPANY
2,1_HARDERSFIELD_1004,1,1004,Jim Beam w/2 Rocks Glasses,750mL,1,16.49,16.49,03-01-2024,750,1,0.79,12546,JIM BEAM BRANDS COMPANY
3,1_HARDERSFIELD_1004,1,1004,Jim Beam w/2 Rocks Glasses,750mL,1,14.49,14.49,08-01-2024,750,1,0.79,12546,JIM BEAM BRANDS COMPANY
4,1_HARDERSFIELD_1005,1,1005,Maker's Mark Combo Pack,375mL 2 Pk,2,69.98,34.99,09-01-2024,375,1,0.79,12546,JIM BEAM BRANDS COMPANY

-------------------------------------------------- vendor_invoice --------------------------------------------------
Count of records: 5543

,VendorNumber,VendorName,InvoiceDate,PONumber,PODate,PayDate,Quantity,Dollars,Freight,Approval
0,105,ALTAMAR BRANDS LLC,04-01-2024,8124,21-12-2023,16-02-2024,6,214.26,3.47,None
1,4466,AMERICAN VINTAGE BEVERAGE,07-01-2024,8137,22-12-2023,21-02-2024,15,140.55,8.57,None
2,388,ATLANTIC IMPORTING COMPANY,09-01-2024,8169,24-12-2023,16-02-2024,5,106.60,4.61,None
3,480,BACARDI USA INC,12-01-2024,8106,20-12-2023,05-02-2024,10100,137483.78,2935.20,None
4,516,BANFI PRODUCTS CORP,07-01-2024,8170,24-12-2023,12-02-2024,1935,15527.25,429.20,None

In [24]:
purchases =pd.read_sql_query("select * from purchases where VendorNumber=4466",conn)
purchases

,InventoryId,Store,Brand,Description,Size,VendorNumber,VendorName,PONumber,PODate,ReceivingDate,InvoiceDate,PayDate,PurchasePrice,Quantity,Dollars,Classification
0,30_CULCHETH_5255,30,5255,TGI Fridays Ultimte Mudslide,1.75L,4466,AMERICAN VINTAGE BEVERAGE,8137,22-12-2023,01-01-2024,07-01-2024,21-02-2024,9.35,4,37.40,1
1,34_PITMERDEN_5215,34,5215,TGI Fridays Long Island Iced,1.75L,4466,AMERICAN VINTAGE BEVERAGE,8137,22-12-2023,02-01-2024,07-01-2024,21-02-2024,9.41,5,47.05,1
2,1_HARDERSFIELD_5255,1,5255,TGI Fridays Ultimte Mudslide,1.75L,4466,AMERICAN VINTAGE BEVERAGE,8137,22-12-2023,01-01-2024,07-01-2024,21-02-2024,9.35,6,56.10,1
3,38_GOULCREST_5215,38,5215,TGI Fridays Long Island Iced,1.75L,4466,AMERICAN VINTAGE BEVERAGE,8207,27-12-2023,07-01-2024,19-01-2024,26-02-2024,9.41,6,56.46,1
4,59_CLAETHORPES_5215,59,5215,TGI Fridays Long Island Iced,1.75L,4466,AMERICAN VINTAGE BEVERAGE,8207,27-12-2023,05-01-2024,19-01-2024,26-02-2024,9.41,6,56.46,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
860,34_PITMERDEN_5215,34,5215,TGI Fridays Long Island Iced,1.75L,4466,AMERICAN VINTAGE BEVERAGE,10777,22-06-2024,28-06-2024,09-07-2024,15-08-2024,9.41,4,37.64,1
861,60_IRRAGIN_5215,60,5215,TGI Fridays Long Island Iced,1.75L,4466,AMERICAN VINTAGE BEVERAGE,10777,22-06-2024,30-06-2024,09-07-2024,15-08-2024,9.41,5,47.05,1
862,60_IRRAGIN_5255,60,5255,TGI Fridays Ultimte Mudslide,1.75L,4466,AMERICAN VINTAGE BEVERAGE,10777,22-06-2024,30-06-2024,09-07-2024,15-08-2024,9.35,2,18.70,1
863,60_IRRAGIN_3140,60,3140,TGI Fridays Orange Dream,1.75L,4466,AMERICAN VINTAGE BEVERAGE,10777,22-06-2024,30-06-2024,09-07-2024,15-08-2024,11.19,6,67.14,1
864,34_PITMERDEN_5255,34,5255,TGI Fridays Ultimte Mudslide,1.75L,4466,AMERICAN VINTAGE BEVERAGE,10777,22-06-2024,28-06-2024,09-07-2024,15-08-2024,9.35,1,9.35,1

In [25]:
purchase_prices=pd.read_sql_query("""Select * from purchase_prices where VendorNumber=4466""",conn)
purchase_prices

,Brand,Description,Price,Size,Volume,Classification,PurchasePrice,VendorNumber,VendorName
0,5215,TGI Fridays Long Island Iced,12.99,1750mL,1750,1,9.41,4466,AMERICAN VINTAGE BEVERAGE
1,5255,TGI Fridays Ultimte Mudslide,12.99,1750mL,1750,1,9.35,4466,AMERICAN VINTAGE BEVERAGE
2,3140,TGI Fridays Orange Dream,14.99,1750mL,1750,1,11.19,4466,AMERICAN VINTAGE BEVERAGE

In [30]:
purchases.groupby(['Brand','PurchasePrice'])[['Quantity','Dollars']].sum()

                     Quantity   Dollars
Brand PurchasePrice
3140  11.19              1552  17366.88
5215  9.41               2267  21332.47
5255  9.35               2135  19962.25

In [33]:
purchase_prices

,Brand,Description,Price,Size,Volume,Classification,PurchasePrice,VendorNumber,VendorName
0,5215,TGI Fridays Long Island Iced,12.99,1750mL,1750,1,9.41,4466,AMERICAN VINTAGE BEVERAGE
1,5255,TGI Fridays Ultimte Mudslide,12.99,1750mL,1750,1,9.35,4466,AMERICAN VINTAGE BEVERAGE
2,3140,TGI Fridays Orange Dream,14.99,1750mL,1750,1,11.19,4466,AMERICAN VINTAGE BEVERAGE

In [34]:
vendor_invoice = pd.read_sql_query(
    "SELECT * FROM vendor_invoice",
    conn
)
vendor_invoice

,VendorNumber,VendorName,InvoiceDate,PONumber,PODate,PayDate,Quantity,Dollars,Freight,Approval
0,105,ALTAMAR BRANDS LLC,04-01-2024,8124,21-12-2023,16-02-2024,6,214.26,3.47,None
1,4466,AMERICAN VINTAGE BEVERAGE,07-01-2024,8137,22-12-2023,21-02-2024,15,140.55,8.57,None
2,388,ATLANTIC IMPORTING COMPANY,09-01-2024,8169,24-12-2023,16-02-2024,5,106.60,4.61,None
3,480,BACARDI USA INC,12-01-2024,8106,20-12-2023,05-02-2024,10100,137483.78,2935.20,None
4,516,BANFI PRODUCTS CORP,07-01-2024,8170,24-12-2023,12-02-2024,1935,15527.25,429.20,None
...,...,...,...,...,...,...,...,...,...,...
5538,9622,WEIN BAUER INC,06-01-2025,13626,21-12-2024,10-02-2025,90,1563.00,8.60,None
5539,9625,WESTERN SPIRITS BEVERAGE CO,10-01-2025,13661,23-12-2024,18-02-2025,4617,37300.48,186.50,None
5540,3664,WILLIAM GRANT & SONS INC,02-01-2025,13643,22-12-2024,04-02-2025,9848,202815.78,932.95,None
5541,9815,WINE GROUP INC,03-01-2025,13602,20-12-2024,08-02-2025,24747,149007.56,819.54,None
5542,90058,ZORVINO VINEYARDS,05-01-2025,13574,18-12-2024,12-02-2025,437,3608.11,16.60,None

In [35]:
sales = pd.read_sql_query("SELECT * FROM sales", conn)

In [36]:
sales

,InventoryId,Store,Brand,Description,Size,SalesQuantity,SalesDollars,SalesPrice,SalesDate,Volume,Classification,ExciseTax,VendorNo,VendorName
0,1_HARDERSFIELD_1004,1,1004,Jim Beam w/2 Rocks Glasses,750mL,1,16.49,16.49,01-01-2024,750,1,0.79,12546,JIM BEAM BRANDS COMPANY
1,1_HARDERSFIELD_1004,1,1004,Jim Beam w/2 Rocks Glasses,750mL,2,32.98,16.49,02-01-2024,750,1,1.57,12546,JIM BEAM BRANDS COMPANY
2,1_HARDERSFIELD_1004,1,1004,Jim Beam w/2 Rocks Glasses,750mL,1,16.49,16.49,03-01-2024,750,1,0.79,12546,JIM BEAM BRANDS COMPANY
3,1_HARDERSFIELD_1004,1,1004,Jim Beam w/2 Rocks Glasses,750mL,1,14.49,14.49,08-01-2024,750,1,0.79,12546,JIM BEAM BRANDS COMPANY
4,1_HARDERSFIELD_1005,1,1005,Maker's Mark Combo Pack,375mL 2 Pk,2,69.98,34.99,09-01-2024,375,1,0.79,12546,JIM BEAM BRANDS COMPANY
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1048570,19_WINTERVALE_39384,19,39384,F Coppola Diamond Pnt Nr,750mL,4,51.80,12.95,12-02-2024,750,2,0.45,2000,SOUTHERN WINE & SPIRITS NE
1048571,19_WINTERVALE_39384,19,39384,F Coppola Diamond Pnt Nr,750mL,8,103.60,12.95,13-02-2024,750,2,0.90,2000,SOUTHERN WINE & SPIRITS NE
1048572,19_WINTERVALE_39384,19,39384,F Coppola Diamond Pnt Nr,750mL,1,12.95,12.95,19-02-2024,750,2,0.11,2000,SOUTHERN WINE & SPIRITS NE
1048573,19_WINTERVALE_39384,19,39384,F Coppola Diamond Pnt Nr,750mL,3,38.85,12.95,22-02-2024,750,2,0.34,2000,SOUTHERN WINE & SPIRITS NE
1048574,19_WINTERVALE_39384,19,39384,F Coppola Diamond Pnt Nr,750mL,2,25.90,12.95,24-02-2024,750,2,0.22,2000,SOUTHERN WINE & SPIRITS NE

In [37]:
vendor_invoice['PONumber'].nunique()

5543

In [38]:
vendor_invoice.shape

(5543, 10)

In [39]:
sales

,InventoryId,Store,Brand,Description,Size,SalesQuantity,SalesDollars,SalesPrice,SalesDate,Volume,Classification,ExciseTax,VendorNo,VendorName
0,1_HARDERSFIELD_1004,1,1004,Jim Beam w/2 Rocks Glasses,750mL,1,16.49,16.49,01-01-2024,750,1,0.79,12546,JIM BEAM BRANDS COMPANY
1,1_HARDERSFIELD_1004,1,1004,Jim Beam w/2 Rocks Glasses,750mL,2,32.98,16.49,02-01-2024,750,1,1.57,12546,JIM BEAM BRANDS COMPANY
2,1_HARDERSFIELD_1004,1,1004,Jim Beam w/2 Rocks Glasses,750mL,1,16.49,16.49,03-01-2024,750,1,0.79,12546,JIM BEAM BRANDS COMPANY
3,1_HARDERSFIELD_1004,1,1004,Jim Beam w/2 Rocks Glasses,750mL,1,14.49,14.49,08-01-2024,750,1,0.79,12546,JIM BEAM BRANDS COMPANY
4,1_HARDERSFIELD_1005,1,1005,Maker's Mark Combo Pack,375mL 2 Pk,2,69.98,34.99,09-01-2024,375,1,0.79,12546,JIM BEAM BRANDS COMPANY
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1048570,19_WINTERVALE_39384,19,39384,F Coppola Diamond Pnt Nr,750mL,4,51.80,12.95,12-02-2024,750,2,0.45,2000,SOUTHERN WINE & SPIRITS NE
1048571,19_WINTERVALE_39384,19,39384,F Coppola Diamond Pnt Nr,750mL,8,103.60,12.95,13-02-2024,750,2,0.90,2000,SOUTHERN WINE & SPIRITS NE
1048572,19_WINTERVALE_39384,19,39384,F Coppola Diamond Pnt Nr,750mL,1,12.95,12.95,19-02-2024,750,2,0.11,2000,SOUTHERN WINE & SPIRITS NE
1048573,19_WINTERVALE_39384,19,39384,F Coppola Diamond Pnt Nr,750mL,3,38.85,12.95,22-02-2024,750,2,0.34,2000,SOUTHERN WINE & SPIRITS NE
1048574,19_WINTERVALE_39384,19,39384,F Coppola Diamond Pnt Nr,750mL,2,25.90,12.95,24-02-2024,750,2,0.22,2000,SOUTHERN WINE & SPIRITS NE

In [40]:
sales.groupby('Brand')[['SalesDollars','SalesPrice','SalesQuantity']].sum()

       SalesDollars  SalesPrice  SalesQuantity
Brand
58          3741.12     2753.88            288
60          1358.76     1086.01            124
61           335.76       27.98             24
62          6552.38     5342.68            162
63          5552.69     4526.93            131
...             ...         ...            ...
90084         63.98       63.98              2
90085         73.98       36.99              2
90086         51.99       51.99              1
90087        469.99      469.99              1
90089       3239.73      599.95             27

[7658 rows x 3 columns]

• The purchases table contains actual purchase data, including the date of purchase, products (brands) purchased by vendors, the amount paid (in dollars), and the quantity purchased.

• The purchase price column is derived from the purchase_prices table, which provides product-wise actual and purchase prices. The combination of vendor and brand is unique in this table.

• The vendor_invoice table aggregates data from the purchases table, summarizing quantity and dollar amounts, along with an additional column for freight. This table maintains uniqueness based on vendor and PO number.

• The sales table captures actual sales transactions, detailing the brands purchased by vendors, the quantity sold, the selling price, and the revenue earned.

As the data that we need for analysis is distributed in different tables,we need to create a summary table containing.
.Purchase transactions made by vendors
.Sales Transaction data
.Freight costs for each vedors
.actual product prices from vendors

In [41]:
vendor_invoice.columns

Index(['VendorNumber', 'VendorName', 'InvoiceDate', 'PONumber', 'PODate',
       'PayDate', 'Quantity', 'Dollars', 'Freight', 'Approval'],
      dtype='object')

In [42]:
freight_summary=pd.read_sql_query("""Select vendorNumber,SUM(Freight) as FreightCost from vendor_invoice
group by VendorNumber""",conn)

In [43]:
freight_summary

     VendorNumber  FreightCost
0               2        27.08
1              54         0.48
2              60       367.52
3             105        62.39
4             200         6.19
..            ...          ...
121         98450       856.02
122         99166       130.09
123        172662       178.34
124        173357       202.50
125        201359         0.09

[126 rows x 2 columns]

In [47]:
pd.read_sql_query("""
SELECT
    p.VendorNumber,
    p.VendorName,
    p.Brand,
    p.PurchasePrice,
    pp.Volume,
    pp.Price AS ActualPrice,
    SUM(p.Quantity) AS TotalPurchaseQuantity,
    SUM(p.Dollars) AS TotalPurchaseDollars
FROM purchases p
JOIN purchase_prices pp
    ON p.Brand = pp.Brand
GROUP BY 
    p.VendorNumber,
    p.VendorName,
    p.Brand,
    p.PurchasePrice,
    pp.Volume,
    pp.Price
ORDER BY TotalPurchaseDollars DESC
""", conn)

,VendorNumber,VendorName,Brand,PurchasePrice,Volume,ActualPrice,TotalPurchaseQuantity,TotalPurchaseDollars
0,1128,BROWN-FORMAN CORP,1233,26.27,1750,36.99,60320,1584606.40
1,3960,DIAGEO NORTH AMERICA INC,4261,16.17,1750,22.99,96073,1553500.41
2,4425,MARTIGNETTI COMPANIES,3405,23.19,1750,28.99,62385,1446708.15
3,17035,PERNOD RICARD USA,8068,18.24,1750,24.99,75385,1375022.40
4,3960,DIAGEO NORTH AMERICA INC,3545,21.89,1750,29.99,58783,1286759.87
...,...,...,...,...,...,...,...,...
8507,9815,WINE GROUP INC,8527,1.32,750,4.99,2,2.64
8508,8004,SAZERAC CO INC,5683,0.39,50,0.49,6,2.34
8509,9815,WINE GROUP INC,22407,2.25,750,3.29,1,2.25
8510,3960,DIAGEO NORTH AMERICA INC,3775,0.73,50,0.99,1,0.73
8511,7245,PROXIMO SPIRITS INC.,3065,0.71,50,0.99,1,0.71

In [48]:
sales.columns

Index(['InventoryId', 'Store', 'Brand', 'Description', 'Size', 'SalesQuantity',
       'SalesDollars', 'SalesPrice', 'SalesDate', 'Volume', 'Classification',
       'ExciseTax', 'VendorNo', 'VendorName'],
      dtype='object')

In [49]:
pd.read_sql_query("""
SELECT
    VendorNo,
    Brand,
    SUM(SalesDollars) AS TotalSalesDollars,
    SUM(SalesPrice) AS TotalSalesPrice,
    SUM(SalesQuantity) AS TotalSalesQuantity,
    SUM(ExciseTax) AS TotalExciseTax
FROM sales
GROUP BY VendorNo, Brand
ORDER BY TotalSalesDollars
""", conn)

,VendorNo,Brand,TotalSalesDollars,TotalSalesPrice,TotalSalesQuantity,TotalExciseTax
0,8004,5287,0.98,0.98,2,0.10
1,3960,3303,0.99,0.99,1,0.05
2,9206,2773,0.99,0.99,1,0.05
3,9625,8872,0.99,0.99,1,0.05
4,3252,3933,1.98,0.99,2,0.10
...,...,...,...,...,...,...
7653,4425,3405,275162.97,52289.50,9203,16909.12
7654,17035,8068,288135.11,48202.30,11189,20557.97
7655,1128,1233,344712.22,64889.97,9578,17598.14
7656,3960,3545,357759.17,52774.51,11883,21833.58
7657,3960,4261,444810.74,43304.31,20226,37163.76

In [52]:
vendor_sales_summary = pd.read_sql_query("""
WITH FreightSummary AS (
    SELECT
        VendorNumber,
        SUM(Freight) AS FreightCost
    FROM vendor_invoice
    GROUP BY VendorNumber
),

PurchaseSummary AS (
    SELECT
        p.VendorNumber,
        p.VendorName,
        p.Brand,
        p.Description,
        p.PurchasePrice,
        pp.Price AS ActualPrice,
        pp.Volume,
        SUM(p.Quantity) AS TotalPurchaseQuantity,
        SUM(p.Dollars) AS TotalPurchaseDollars
    FROM purchases p
    JOIN purchase_prices pp
        ON p.Brand = pp.Brand
    WHERE p.PurchasePrice > 0
    GROUP BY
        p.VendorNumber,
        p.VendorName,
        p.Brand,
        p.Description,
        p.PurchasePrice,
        pp.Price,
        pp.Volume
),

SalesSummary AS (
    SELECT
        VendorNo,
        Brand,
        SUM(SalesQuantity) AS TotalSalesQuantity,
        SUM(SalesDollars) AS TotalSalesDollars,
        SUM(SalesPrice) AS TotalSalesPrice,
        SUM(ExciseTax) AS TotalExciseTax
    FROM sales
    GROUP BY VendorNo, Brand
)

SELECT
    ps.VendorNumber,
    ps.VendorName,
    ps.Brand,
    ps.Description,
    ps.PurchasePrice,
    ps.ActualPrice,
    ps.Volume,
    ps.TotalPurchaseQuantity,
    ps.TotalPurchaseDollars,
    ss.TotalSalesQuantity,
    ss.TotalSalesDollars,
    ss.TotalSalesPrice,
    ss.TotalExciseTax,
    fs.FreightCost
FROM PurchaseSummary ps
LEFT JOIN SalesSummary ss
    ON ps.VendorNumber = ss.VendorNo
    AND ps.Brand = ss.Brand
LEFT JOIN FreightSummary fs
    ON ps.VendorNumber = fs.VendorNumber
ORDER BY ps.TotalPurchaseDollars DESC
""", conn)

In [53]:
vendor_sales_summary

,VendorNumber,VendorName,Brand,Description,PurchasePrice,ActualPrice,Volume,TotalPurchaseQuantity,TotalPurchaseDollars,TotalSalesQuantity,TotalSalesDollars,TotalSalesPrice,TotalExciseTax,FreightCost
0,1128,BROWN-FORMAN CORP,1233,Jack Daniels No 7 Black,26.27,36.99,1750,60320,1584606.40,9578.0,344712.22,64889.97,17598.14,68601.68
1,3960,DIAGEO NORTH AMERICA INC,4261,Capt Morgan Spiced Rum,16.17,22.99,1750,96073,1553500.41,20226.0,444810.74,43304.31,37163.76,257032.07
2,4425,MARTIGNETTI COMPANIES,3405,Tito's Handmade Vodka,23.19,28.99,1750,62385,1446708.15,9203.0,275162.97,52289.50,16909.12,144929.24
3,17035,PERNOD RICARD USA,8068,Absolut 80 Proof,18.24,24.99,1750,75385,1375022.40,11189.0,288135.11,48202.30,20557.97,123780.22
4,3960,DIAGEO NORTH AMERICA INC,3545,Ketel One Vodka,21.89,29.99,1750,58783,1286759.87,11883.0,357759.17,52774.51,21833.58,257032.07
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8507,9815,WINE GROUP INC,8527,Concannon Glen Ellen Wh Zin,1.32,4.99,750,2,2.64,3.0,5.97,5.97,0.33,27100.41
8508,8004,SAZERAC CO INC,5683,Dr McGillicuddy's Apple Pie,0.39,0.49,50,6,2.34,128.0,62.72,0.98,6.72,50293.62
8509,9815,WINE GROUP INC,22407,Three Wishes Chard,2.25,3.29,750,1,2.25,1.0,3.29,3.29,0.11,27100.41
8510,3960,DIAGEO NORTH AMERICA INC,3775,Smirnoff Sorbet Pine/Coconut,0.73,0.99,50,1,0.73,NaN,NaN,NaN,NaN,257032.07
8511,7245,PROXIMO SPIRITS INC.,3065,Three Olives Grape Vodka,0.71,0.99,50,1,0.71,81.0,80.19,29.70,4.21,38994.78

Performance Optimization

The query involves heavy joins and aggregations on large datasets such as sales and purchases.

Storing the pre-aggregated results avoids repeated expensive computations.

It helps in analyzing sales, purchases, and pricing for different vendors and brands.

Storing this processed data enables faster dashboard creation and reporting in the future.

Instead of running complex queries every time, dashboards can quickly fetch data from the vendor_sales_summary table.

In [54]:
vendor_sales_summary.dtypes

VendorNumber               int64
VendorName                object
Brand                      int64
Description               object
PurchasePrice            float64
ActualPrice              float64
Volume                    object
TotalPurchaseQuantity      int64
TotalPurchaseDollars     float64
TotalSalesQuantity       float64
TotalSalesDollars        float64
TotalSalesPrice          float64
TotalExciseTax           float64
FreightCost              float64
dtype: object

In [55]:
vendor_sales_summary.isnull().sum()

VendorNumber                0
VendorName                  0
Brand                       0
Description                 0
PurchasePrice               0
ActualPrice                 0
Volume                      0
TotalPurchaseQuantity       0
TotalPurchaseDollars        0
TotalSalesQuantity       1633
TotalSalesDollars        1633
TotalSalesPrice          1633
TotalExciseTax           1633
FreightCost                 0
dtype: int64

In [56]:
vendor_sales_summary['VendorName'].unique()

array(['BROWN-FORMAN CORP          ', 'DIAGEO NORTH AMERICA INC   ',
       'MARTIGNETTI COMPANIES', 'PERNOD RICARD USA          ',
       'BACARDI USA INC            ', 'JIM BEAM BRANDS COMPANY    ',
       'ULTRA BEVERAGE COMPANY LLP ', 'PROXIMO SPIRITS INC.       ',
       'MAJESTIC FINE WINES        ', 'STOLI GROUP,(USA) LLC      ',
       'CAMPARI AMERICA            ', 'SAZERAC CO INC             ',
       'MOET HENNESSY USA INC      ', 'M S WALKER INC             ',
       'CONSTELLATION BRANDS INC   ', 'SAZERAC NORTH AMERICA INC. ',
       'REMY COINTREAU USA INC     ', 'SIDNEY FRANK IMPORTING CO  ',
       'WILLIAM GRANT & SONS INC   ', 'PALM BAY INTERNATIONAL INC ',
       'E & J GALLO WINERY         ', 'HEAVEN HILL DISTILLERIES   ',
       'CASTLE BRANDS CORP.        ', 'SOUTHERN WINE & SPIRITS NE ',
       'DISARONNO INTERNATIONAL LLC', 'EDRINGTON AMERICAS         ',
       'TRINCHERO FAMILY ESTATES   ', 'STE MICHELLE WINE ESTATES  ',
       'WINE GROUP INC             ', 'PERFECTA WINES             ',
       'LUXCO INC                  ', 'SHAW ROSS INT L IMP LTD    ',
       'TREASURY WINE ESTATES      ', 'MHW LTD                    ',
       'PHILLIPS PRODUCTS CO.      ', 'KOBRAND CORPORATION        ',
       'BANFI PRODUCTS CORP        ', 'STATE WINE & SPIRITS   ',
       'DIAGEO CHATEAU ESTATE WINES', 'CALEDONIA SPIRITS INC      ',
       'PINE STATE TRADING CO      ', 'VINEYARD BRANDS INC        ',
       'FABRIZIA SPIRITS LLC       ', 'LATITUDE BEVERAGE COMPANY  ',
       'DELICATO VINEYARDS INC     ', 'OLE SMOKY DISTILLERY LLC   ',
       'Serralles Usa LLC          ', 'DUGGANS DISTILLED PRODUCTS ',
       'KLIN SPIRITS LLC           ', 'LAIRD & CO                 ',
       'SEA HAGG DISTILLERY LLC    ', 'Dunn Wine Brokers          ',
       'WESTERN SPIRITS BEVERAGE CO', 'CHARLES JACQUIN ET CIE INC ',
       'FLAG HILL WINERY & VINEYARD', 'FREDERICK WILDMAN & SONS   ',
       'MCCORMICK DISTILLING CO    ', 'MARSALLE COMPANY           ',
       'MANGO BOTTLING INC         ', 'SWEET BABY VINEYARD        ',
       'AMERICAN VINTAGE BEVERAGE  ', 'LABELLE VYDS AND WINERY    ',
       'VRANKEN AMERICA            ', 'PREMIUM PORT WINES, INC.   ',
       'ATLANTIC IMPORTING COMPANY ', 'PREMIER DISTRIBUTORS       ',
       'Russian Standard Vodka     ', 'NICHE W & S                ',
       'WEIN BAUER INC             ', 'BULLY BOY DISTILLERS       ',
       'VINILANDIA USA             ', 'TAKARA SAKE USA INC        ',
       'PSP WINES ', 'ADAMBA IMPORTS INTL INC    ',
       'TY KU LLC                  ', 'MARTIGNETTI COMPANIES ',
       'ZORVINO VINEYARDS          ', 'SMOKY QUARTZ DISTILLERY LLC',
       'CRUSH WINES                ', 'TAMWORTH DISTILLING        ',
       'MOONLIGHT MEADERY          ', 'ALISA CARR BEVERAGES           ',
       'POVERTY LANE ORCHARDS      ', 'SEA BREEZE CELLARS LLC     ',
       'VINEXTRA INC               ', 'SWEETWATER FARM         ',
       'FORTUNE WINE BROKERS LLC   ', 'DJINN SPIRITS LLC          ',
       'JEWELL TOWNE VINEYARDS     ',
       'IRA GOLDMAN AND WILLIAMS, LLP          ',
       'Circa Wines                ', 'HOOD RIVER DISTILLERS, Inc.',
       'INCREDIBREW INC            ', 'ALTAMAR BRANDS LLC         ',
       'CANDIA VINEYARDS           ', 'SURVILLE ENTERPRISES CORP  ',
       'TALL SHIP DISTILLERY LLC   ', 'BLACK PRINCE DISTILLERY INC',
       'STELLAR IMPORTING CO LLC   ', 'VINEDREA WINES LLC         ',
       'FULCHINO VINEYARD INC      ', 'STAR INDUSTRIES INC.       ',
       'WALPOLE MTN VIEW WINERY    ', 'HAUNTING WHISPER VYDS      ',
       'R.P.IMPORTS INC            ', 'THE PIERPONT GROUP LLC     ',
       'THE IMPORTED GRAPE LLC     ', 'BLACK ROCK SPIRITS LLC     ',
       'CENTEUR IMPORTS LLC        ', 'BRONCO WINE COMPANY        ',
       'PARK STREET IMPORTS LLC    ', 'APPOLO VINEYARDS LLC       ',
       'HIGHLAND WINE MERCHANTS LLC', 'MILTONS DISTRIBUTING CO    ',
       'SILVER MOUNTAIN CIDERS     ', 'FANTASY FINE WINES CORP    ',
       'CAPSTONE INTERNATIONAL     ', 'UNCORKED       '], dtype=object)

In [57]:
vendor_sales_summary['Description'].unique()

array(['Jack Daniels No 7 Black', 'Capt Morgan Spiced Rum',
       "Tito's Handmade Vodka", ..., 'Smirnoff Light Strawberry',
       'Concannon Glen Ellen Wh Zin', 'Three Wishes Chard'],
      shape=(7657,), dtype=object)

In [61]:
vendor_sales_summary['Volume']=vendor_sales_summary['Volume'].astype('float64')

In [62]:
vendor_sales_summary.fillna(0,inplace=True)

In [63]:
vendor_sales_summary['VendorName'] = vendor_sales_summary['VendorName'].str.strip()

In [64]:
vendor_sales_summary['GrossProfit'] = vendor_sales_summary['TotalSalesDollars'] - vendor_sales_summary['TotalPurchaseDollars']

In [65]:
vendor_sales_summary['ProfitMargin'] = (vendor_sales_summary['GrossProfit'] / vendor_sales_summary['TotalSalesDollars']) * 100

In [66]:
vendor_sales_summary['StockTurnover'] = vendor_sales_summary['TotalSalesQuantity'] / vendor_sales_summary['TotalPurchaseQuantity']

In [67]:
vendor_sales_summary['SalestoPurchaseRatio'] = vendor_sales_summary['TotalSalesDollars'] / vendor_sales_summary['TotalPurchaseDollars']

In [68]:
cursor = conn.cursor()

cursor.execute("""
CREATE TABLE vendor_sales_summary (
    VendorNumber INT,
    VendorName VARCHAR(100),
    Brand INT,
    Description VARCHAR(100),
    PurchasePrice DECIMAL(10,2),
    ActualPrice DECIMAL(10,2),
    Volume FLOAT,
    TotalPurchaseQuantity INT,
    TotalPurchaseDollars DECIMAL(15,2),
    TotalSalesQuantity INT,
    TotalSalesDollars DECIMAL(15,2),
    TotalSalesPrice DECIMAL(15,2),
    TotalExciseTax DECIMAL(15,2),
    FreightCost DECIMAL(15,2),
    GrossProfit DECIMAL(15,2),
    ProfitMargin DECIMAL(15,2),
    StockTurnover DECIMAL(15,2),
    SalestoPurchaseRatio DECIMAL(15,2),
    PRIMARY KEY (VendorNumber, Brand)
);
""")

In [69]:
pd.read_sql_query("select * from vendor_sales_summary", conn)

Empty DataFrame
Columns: [VendorNumber, VendorName, Brand, Description, PurchasePrice, ActualPrice, Volume, TotalPurchaseQuantity, TotalPurchaseDollars, TotalSalesQuantity, TotalSalesDollars, TotalSalesPrice, TotalExciseTax, FreightCost, GrossProfit, ProfitMargin, StockTurnover, SalestoPurchaseRatio]
Index: []

In [70]:
vendor_sales_summary.to_sql('vendor_sales_summary', conn, if_exists='replace', index=False)

8512